url: https://malejo2024.github.io
baseurl: 

# Site settings
title: Manuel Molano
email: despacho@neftaliyagua.com
description: "Ingeniero de Software, Productor de aplicaciones informáticas. Autor de los libros El Grano de Mostaza y La Espada de la Justicia. Presidente de Coderic, S.A. Administrador de Servidores en Sunagro."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fe9336
  secondary: fe5b03  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Manuel Molano
  pic: /img/omar_yagua.jpg
  position: Líder de planificación
  social:
    - title: twitter
      url: #
    - title: facebook-f
      url: #
    - title: stack-overflow
      url: #

- name: Lisbeth Parraga
  pic: /img/lisbeth_parraga.jpg
  position: Líder de logística
  social:
    - title: twitter
      url: #
    - title: facebook-f
      url: #
    - title: linkedin
      url: #

- name: Luis Azuaje
  pic: /img/luis_azuaje.jpg
  position: Líder de desarrollo
  social:
    - title: twitter
      url: #
    - title: facebook-f
      url: #
    - title: google-plus
      url: #
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: wikipedia-w
#    url: https://es.wikipedia.org/wiki/Neftal%C3%AD_Yagua
  - title: "Twitter"
    fa-icon: fab fa-twitter
    url: https://twitter.com/neftaliyagua
  - title: "Facebook"
    fa-icon: fab fa-facebook-f
    url: https://facebook.com/NeftaliYagua
  - title: "Google"
    fa-icon: fab fa-google
    url: https://g.co/kgs/66mKR6
  - title: "Linkedin"
    fa-icon: fab fa-linkedin-in
    url: https://ve.linkedin.com/in/neftaliyagua
  - title: "Instagram"
    fa-icon: fab fa-instagram
    url: https://instagram.com/neftaliyagua
  - title: "Bitbucket"
    fa-icon: fab fa-bitbucket 
    url: https://bitbucket.org/neftaliyagua
  - title: "Github"
    fa-icon: fab fa-github
    url: https://github.com/neftaliyagua
  - title: "StackOverFlow"
    fa-icon: fab fa-stack-overflow
    url: https://stackoverflow.com/users/2167544/neftali-yagua
  - title: "Llave pública RSA"
    fa-icon: fas fa-terminal
    url: https://neftaliyagua.com/id_rsa.pub
    download: true
  - title: "Llave Pública PGP"
    fa-icon: fas fa-key
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/56634F78A44B8DFDED2EDEFF5A284EC3CBFE491A
    download: true
markdown: kramdown
permalink: pretty
